/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.timnas.sistembengkelmotor.view;

import edu.timnas.sistembengkelmotor.controller.KasirController;
import edu.timnas.sistembengkelmotor.database.SistemBengkelMotorDatabase;
import edu.timnas.sistembengkelmotor.entity.Kasir;
import edu.timnas.sistembengkelmotor.error.KasirException;
import edu.timnas.sistembengkelmotor.event.KasirListener;
import edu.timnas.sistembengkelmotor.model.KasirModel;
import edu.timnas.sistembengkelmotor.model.TabelKasirModel;
import edu.timnas.sistembengkelmotor.service.KasirDao;
import java.sql.SQLException;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.text.DefaultEditorKit;

/**
 *
 * @author teguhsis
 */
public class KasirView extends javax.swing.JPanel implements KasirListener, ListSelectionListener{

    private TabelKasirModel tabelModel;
    private KasirModel model;
    private KasirController controller;
    
    public KasirView() {
        tabelModel = new TabelKasirModel();
        
        model = new KasirModel();
        model.setListener(this);
        
        controller = new KasirController();
        controller.setModel(model);
        
        initComponents();
        
        tableKasir.getSelectionModel().addListSelectionListener(this);
        
        tableKasir.setModel(tabelModel);
    }

    public JTable getTableKasir() {
        return tableKasir;
    }

    public JTextField getTxtKasirAlamat() {
        return txtKasirAlamat;
    }

    public JTextField getTxtKasirId() {
        return txtKasirId;
    }

    public JTextField getTxtKasirNama() {
        return txtKasirNama;
    }

    public JTextField getTxtKasirNoTelp() {
        return txtKasirNoTelp;
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtKasirNama = new javax.swing.JTextField();
        txtKasirAlamat = new javax.swing.JTextField();
        txtKasirId = new javax.swing.JTextField();
        txtKasirNoTelp = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableKasir = new javax.swing.JTable();
        btnKasirDelete = new javax.swing.JButton();
        btnKasirSave = new javax.swing.JButton();
        btnKasirReset = new javax.swing.JButton();
        btnKasirUpdate = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Manajemen Data Kasir");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("IDKasir");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Nama Kasir");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Alamat Kasir");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Telp");

        txtKasirAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKasirAlamatActionPerformed(evt);
            }
        });

        txtKasirId.setEditable(false);
        txtKasirId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKasirIdActionPerformed(evt);
            }
        });

        tableKasir.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableKasir);

        btnKasirDelete.setText("DELETE");
        btnKasirDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKasirDeleteActionPerformed(evt);
            }
        });

        btnKasirSave.setText("SAVE");
        btnKasirSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKasirSaveActionPerformed(evt);
            }
        });

        btnKasirReset.setText("RESET");
        btnKasirReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKasirResetActionPerformed(evt);
            }
        });

        btnKasirUpdate.setText("UPDATE");
        btnKasirUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKasirUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtKasirNama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtKasirAlamat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtKasirNoTelp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtKasirId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnKasirReset)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnKasirSave)
                                .addGap(18, 18, 18)
                                .addComponent(btnKasirUpdate)
                                .addGap(14, 14, 14)
                                .addComponent(btnKasirDelete)
                                .addGap(8, 8, 8))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(299, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtKasirId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtKasirNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtKasirAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtKasirNoTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKasirDelete)
                    .addComponent(btnKasirReset)
                    .addComponent(btnKasirSave)
                    .addComponent(btnKasirUpdate))
                .addGap(229, 229, 229))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtKasirIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKasirIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKasirIdActionPerformed

    private void txtKasirAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKasirAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKasirAlamatActionPerformed

    private void btnKasirResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKasirResetActionPerformed
        // TODO add your handling code here:
        controller.resetKasir(this);
    }//GEN-LAST:event_btnKasirResetActionPerformed

    private void btnKasirSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKasirSaveActionPerformed
        // TODO add your handling code here:
        controller.insertKasir(this);
    }//GEN-LAST:event_btnKasirSaveActionPerformed

    private void btnKasirUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKasirUpdateActionPerformed
        // TODO add your handling code here:
        controller.updateKasir(this);
    }//GEN-LAST:event_btnKasirUpdateActionPerformed

    private void btnKasirDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKasirDeleteActionPerformed
        // TODO add your handling code here:
        controller.deleteKasir(this);
    }//GEN-LAST:event_btnKasirDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKasirDelete;
    private javax.swing.JButton btnKasirReset;
    private javax.swing.JButton btnKasirSave;
    private javax.swing.JButton btnKasirUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tableKasir;
    private javax.swing.JTextField txtKasirAlamat;
    private javax.swing.JTextField txtKasirId;
    private javax.swing.JTextField txtKasirNama;
    private javax.swing.JTextField txtKasirNoTelp;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onChange(KasirModel model) {
        txtKasirId.setText(model.getIdKasir() + "");
        txtKasirNama.setText(model.getNamaKasir());
        txtKasirAlamat.setText(model.getAlamatKasir());
        txtKasirNoTelp.setText(model.getNoTelp());   
    }

    @Override
    public void onInsert(Kasir kasir) {
        tabelModel.add(kasir);
    }

    @Override
    public void onDelete() {
        int index = tableKasir.getSelectedRow();
        tabelModel.remove(index);
    }

    @Override
    public void onUpdate(Kasir kasir) {
        int index = tableKasir.getSelectedRow();
        tabelModel.set(index, kasir);
    }

    @Override
    public void valueChanged(ListSelectionEvent e) {
        try {
            Kasir model = tabelModel.get(tableKasir.getSelectedRow());
            txtKasirId.setText(model.getIdKasir() + "");
            txtKasirNama.setText(model.getNamaKasir());
            txtKasirAlamat.setText(model.getAlamatKasir());
            txtKasirNoTelp.setText(model.getNoTelp());   
        } catch (IndexOutOfBoundsException exception) {
            
        }
    }
    
    public void loadDatabase() throws SQLException, KasirException{
        KasirDao dao = SistemBengkelMotorDatabase.getKasirDao();
        tabelModel.setList(dao.selectAllKasir());
    }
}
