/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.timnas.sistembengkelmotor.view;

import edu.timnas.sistembengkelmotor.controller.KategoriOnderdilController;
import edu.timnas.sistembengkelmotor.database.SistemBengkelMotorDatabase;
import edu.timnas.sistembengkelmotor.entity.KategoriOnderdil;
import edu.timnas.sistembengkelmotor.error.KategoriOnderdilException;
import edu.timnas.sistembengkelmotor.event.KategoriOnderdilListener;
import edu.timnas.sistembengkelmotor.model.KategoriOnderdilModel;
import edu.timnas.sistembengkelmotor.model.TabelKategoriOnderdilModel;
import edu.timnas.sistembengkelmotor.service.KategoriOnderdilDao;
import java.sql.SQLException;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author teguhsis
 */
public class KategoriOnderdilView extends javax.swing.JPanel implements KategoriOnderdilListener, ListSelectionListener{

    private TabelKategoriOnderdilModel tabelModel;
    private KategoriOnderdilModel model;
    private KategoriOnderdilController controller;
    
    
    public KategoriOnderdilView() {
        tabelModel = new TabelKategoriOnderdilModel();
        
        model = new KategoriOnderdilModel();
        model.setListener(this);
        
        controller = new KategoriOnderdilController();
        controller.setModel(model);
        
        initComponents();
        
//        menampilkan ke form textFields dari tabel yg dipili untuk di-update
        tableKaton.getSelectionModel().addListSelectionListener(this);
        
        
        tableKaton.setModel(tabelModel);
    }

    public JTable getTableKaton() {
        return tableKaton;
    }

    public JTextField getTxtKatonId() {
        return txtKatonId;
    }

    public JTextField getTxtKatonNama() {
        return txtKatonNama;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtKatonNama = new javax.swing.JTextField();
        txtKatonId = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableKaton = new javax.swing.JTable();
        btnKatonReset = new javax.swing.JButton();
        btnKatonSave = new javax.swing.JButton();
        btnKatonUpdate = new javax.swing.JButton();
        btnKatonDelete = new javax.swing.JButton();

        jLabel1.setText("Manajemen Kategori Onderdil");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("ID Kategori");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Nama Kategori");

        txtKatonId.setEditable(false);

        tableKaton.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableKaton);

        btnKatonReset.setText("RESET");
        btnKatonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKatonResetActionPerformed(evt);
            }
        });

        btnKatonSave.setText("SAVE");
        btnKatonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKatonSaveActionPerformed(evt);
            }
        });

        btnKatonUpdate.setText("UPDATE");
        btnKatonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKatonUpdateActionPerformed(evt);
            }
        });

        btnKatonDelete.setText("DELETE");
        btnKatonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKatonDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtKatonNama, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtKatonId, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnKatonReset)
                                .addGap(18, 18, 18)
                                .addComponent(btnKatonSave)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnKatonUpdate)
                                .addGap(18, 18, 18)
                                .addComponent(btnKatonDelete))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtKatonId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtKatonNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKatonReset)
                    .addComponent(btnKatonSave)
                    .addComponent(btnKatonUpdate)
                    .addComponent(btnKatonDelete))
                .addGap(155, 155, 155))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnKatonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKatonSaveActionPerformed
        // TODO add your handling code here:
        controller.insertKategoriOnderdil(this);
    }//GEN-LAST:event_btnKatonSaveActionPerformed

    private void btnKatonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKatonResetActionPerformed
        // TODO add your handling code here:
        controller.resetKategoriOnderdil(this);
    }//GEN-LAST:event_btnKatonResetActionPerformed

    private void btnKatonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKatonUpdateActionPerformed
        // TODO add your handling code here:
        controller.updateKategoriOnderdil(this);
    }//GEN-LAST:event_btnKatonUpdateActionPerformed

    private void btnKatonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKatonDeleteActionPerformed
        // TODO add your handling code here:
        controller.deleteKategoriOnderdil(this);
    }//GEN-LAST:event_btnKatonDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKatonDelete;
    private javax.swing.JButton btnKatonReset;
    private javax.swing.JButton btnKatonSave;
    private javax.swing.JButton btnKatonUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableKaton;
    private javax.swing.JTextField txtKatonId;
    private javax.swing.JTextField txtKatonNama;
    // End of variables declaration//GEN-END:variables
    
    
//    hasil implements dari KategoriOnderdilListener
    @Override
    public void onChange(KategoriOnderdilModel model) {
        txtKatonId.setText(model.getIdKaton()+"");
        txtKatonNama.setText(model.getNamaKaton());
    }

    @Override
    public void onInsert(KategoriOnderdil kategoriOnderdil) {
        tabelModel.add(kategoriOnderdil);
    }

    @Override
    public void onDelete() {
        int index = tableKaton.getSelectedRow() ;
        tabelModel.remove(index);
    }

    @Override
    public void onUpdate(KategoriOnderdil kategoriOnderdil) {
        int index = tableKaton.getSelectedRow() ;
        tabelModel.set(index, kategoriOnderdil);
    }

    
//    implements dari ListSelectionListener
    @Override
    public void valueChanged(ListSelectionEvent lse) {
        try {
            KategoriOnderdil model = tabelModel.get(tableKaton.getSelectedRow());
            txtKatonId.setText(model.getIdKaton()+"");
            txtKatonNama.setText(model.getNamaKaton());
        } catch (IndexOutOfBoundsException  exception) {
            
        }
    }
    
    public void  loadDatatabase() throws SQLException, KategoriOnderdilException{
        KategoriOnderdilDao dao = SistemBengkelMotorDatabase.getKategoriOnderdilDao();
        tabelModel.setList(dao.selectAllKategoriOnderdil());
    }
    
}
