/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.timnas.sistembengkelmotor.view;

import edu.timnas.sistembengkelmotor.error.KategoriOnderdilException;
import java.sql.SQLException;

/**
 *
 * @author teguhsis
 */
public class MainViewKategoriOnderdil extends javax.swing.JFrame {

    /**
     * Creates new form MainViewKategoriOnderdil
     */
    public MainViewKategoriOnderdil() {
        initComponents();
    }

    public void loadDatatabase() throws SQLException, KategoriOnderdilException {
        kategoriOnderdilView1.loadDatatabase();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kategoriOnderdilView1 = new edu.timnas.sistembengkelmotor.view.KategoriOnderdilView();

        getContentPane().add(kategoriOnderdilView1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
        /*  Method main bisa dihapus aja*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private edu.timnas.sistembengkelmotor.view.KategoriOnderdilView kategoriOnderdilView1;
    // End of variables declaration//GEN-END:variables
}
