/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.timnas.sistembengkelmotor.view;

import edu.timnas.sistembengkelmotor.error.KasirException;
import edu.timnas.sistembengkelmotor.error.OnderdilException;
import java.sql.SQLException;

/**
 *
 * @author teguhsis
 */
public class MainViewOnderdil extends javax.swing.JFrame {

    /**
     * Creates new form MainViewOnderdil
     */
    public MainViewOnderdil() {
        initComponents();
    }
    
     public void loadDatabase()throws SQLException, OnderdilException{
        onderdilView1.loadDatabase();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        onderdilView1 = new edu.timnas.sistembengkelmotor.view.OnderdilView();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().add(onderdilView1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private edu.timnas.sistembengkelmotor.view.OnderdilView onderdilView1;
    // End of variables declaration//GEN-END:variables
}
