/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.timnas.sistembengkelmotor.view;

import edu.timnas.sistembengkelmotor.error.RakException;
import java.sql.SQLException;

/**
 *
 * @author teguhsis
 */
public class MainViewRak extends javax.swing.JFrame {

    /**
     * Creates new form MainViewRak
     */
    public MainViewRak() {
        initComponents();
    }
    
    public void loadDatabase()throws SQLException ,RakException{
        rakView1.loadDatabase();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rakView1 = new edu.timnas.sistembengkelmotor.view.RakView();

        getContentPane().add(rakView1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private edu.timnas.sistembengkelmotor.view.RakView rakView1;
    // End of variables declaration//GEN-END:variables
}
