/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.timnas.sistembengkelmotor.view;

import edu.timnas.sistembengkelmotor.controller.OnderdilController;
import edu.timnas.sistembengkelmotor.database.SistemBengkelMotorDatabase;
import edu.timnas.sistembengkelmotor.entity.KategoriOnderdil;
import edu.timnas.sistembengkelmotor.entity.Onderdil;
import edu.timnas.sistembengkelmotor.error.OnderdilException;
import edu.timnas.sistembengkelmotor.event.OnderdilListener;
import edu.timnas.sistembengkelmotor.model.OnderdilModel;
import edu.timnas.sistembengkelmotor.model.TabelOnderdilModel;
import edu.timnas.sistembengkelmotor.service.KategoriOnderdilDao;
import edu.timnas.sistembengkelmotor.service.OnderdilDao;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author teguhsis
 */
public class OnderdilView extends javax.swing.JPanel implements OnderdilListener, ListSelectionListener{

    private TabelOnderdilModel tabelModel;
    private OnderdilModel model;
    private OnderdilController controller;
    
    public OnderdilView() {
        tabelModel = new TabelOnderdilModel();
        
        model = new OnderdilModel();
        model.setListener(this);
        
        controller = new OnderdilController();
        controller.setModel(model);
        
        initComponents();
        
        tableOnderdil.getSelectionModel().addListSelectionListener(this);
        
        tableOnderdil.setModel(tabelModel);
    }

    public JTable getTableOnderdil() {
        return tableOnderdil;
    }

    public JTextField getTxtOnderdilSatuan() {
        return txtOnderdilSatuan;
    }

    public JTextField getTxtOnderdilId() {
        return txtOnderdilId;
    }
    
    public JTextField getTxtOnderdilIdKaton() {
        return txtOnderdilIdKaton;
    }
    
    public JTextField getTxtOnderdilIdRak() {
        return txtOnderdilIdRak;
    }

    public JTextField getTxtOnderdilNamaOnderdil() {
        return txtOnderdilNamaOnderdil;
    }

    public JTextField getTxtOnderdilStok() {
        return txtOnderdilStok;
    }
    
    public JTextField getTxtOnderdilHarhaJual() {
        return txtOnderdilHargaJual;
    }

//    public void comboKategoriOnderdil() throws SQLException{
//        String selectAll = "SELECT * FROM kategoriOnderdil";
//        try {
//            KategoriOnderdilDao dao = SistemBengkelMotorDatabase.getKategoriOnderdilDao();
//            KategoriOnderdil kategoriOnderdil = new KategoriOnderdil();
//        
//        Statement statement = null;
//        ResultSet result = statement.executeQuery(selectAll);
//        KategoriOnderdil katon = null;
//        
//        
//        while(result.next()){
//            Object[] ob = new Object[3];
//            ob[0] = result.getString(1);
//            
//            cmbOnderdilKaton.addItem((String) ob[0]);                                      // fungsi ini bertugas menampung isi dari database
//        }
////        result.close(); statement.close();
//         
//        } catch (Exception e) {
//            System.out.println(e.getMessage());
//
//    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtOnderdilIdRak = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtOnderdilIdKaton = new javax.swing.JTextField();
        txtOnderdilSatuan = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtOnderdilHargaJual = new javax.swing.JTextField();
        txtOnderdilNamaOnderdil = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtOnderdilId = new javax.swing.JTextField();
        txtOnderdilStok = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableOnderdil = new javax.swing.JTable();
        btnOnderdilDelete = new javax.swing.JButton();
        btnOnderdilUpdate = new javax.swing.JButton();
        btnOnderdilSave = new javax.swing.JButton();
        btnOnderdilReset = new javax.swing.JButton();
        cmbOnderdilKaton = new javax.swing.JComboBox<>();

        setBackground(java.awt.Color.white);

        jLabel8.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        jLabel8.setText("Manajemen Onderdil");

        jLabel14.setText("Lokasi/Rak");

        jLabel17.setText("Jumlah");

        jLabel13.setText("Kategori");

        jLabel12.setText("ID Onderdil");

        jLabel18.setText("Satuan");

        jLabel15.setText("Nama");

        jLabel16.setText("Harga Jual ");

        txtOnderdilId.setEditable(false);
        txtOnderdilId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOnderdilIdActionPerformed(evt);
            }
        });

        tableOnderdil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableOnderdil);

        btnOnderdilDelete.setText("DELETE");
        btnOnderdilDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOnderdilDeleteActionPerformed(evt);
            }
        });

        btnOnderdilUpdate.setText("UPDATE");
        btnOnderdilUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOnderdilUpdateActionPerformed(evt);
            }
        });

        btnOnderdilSave.setText("SAVE");
        btnOnderdilSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOnderdilSaveActionPerformed(evt);
            }
        });

        btnOnderdilReset.setText("RESET");
        btnOnderdilReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOnderdilResetActionPerformed(evt);
            }
        });

        cmbOnderdilKaton.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbOnderdilKaton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOnderdilKatonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1056, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnOnderdilReset)
                                .addGap(138, 138, 138)
                                .addComponent(btnOnderdilSave)
                                .addGap(18, 18, 18)
                                .addComponent(btnOnderdilUpdate)
                                .addGap(18, 18, 18)
                                .addComponent(btnOnderdilDelete))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(cmbOnderdilKaton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                            .addGap(12, 12, 12)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtOnderdilId, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtOnderdilIdKaton, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtOnderdilIdRak, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtOnderdilNamaOnderdil, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(27, 27, 27)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel18)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtOnderdilSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel17)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtOnderdilStok, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel16)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtOnderdilHargaJual, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(cmbOnderdilKaton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOnderdilReset)
                    .addComponent(btnOnderdilUpdate)
                    .addComponent(btnOnderdilSave)
                    .addComponent(btnOnderdilDelete))
                .addGap(97, 97, 97))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jLabel8)
                    .addGap(34, 34, 34)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(txtOnderdilId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(14, 14, 14)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(txtOnderdilIdKaton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16)
                        .addComponent(txtOnderdilHargaJual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(11, 11, 11)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(txtOnderdilIdRak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17)
                        .addComponent(txtOnderdilStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(txtOnderdilNamaOnderdil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18)
                        .addComponent(txtOnderdilSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtOnderdilIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOnderdilIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOnderdilIdActionPerformed

    private void btnOnderdilResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOnderdilResetActionPerformed
        // TODO add your handling code here:
        controller.resetOnderdil(this);
    }//GEN-LAST:event_btnOnderdilResetActionPerformed

    private void btnOnderdilSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOnderdilSaveActionPerformed
        // TODO add your handling code here:
        controller.insertOnderdil(this);
    }//GEN-LAST:event_btnOnderdilSaveActionPerformed

    private void btnOnderdilUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOnderdilUpdateActionPerformed
        // TODO add your handling code here:
        controller.updateOnderdil(this);
    }//GEN-LAST:event_btnOnderdilUpdateActionPerformed

    private void btnOnderdilDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOnderdilDeleteActionPerformed
        // TODO add your handling code here:
        controller.deleteOnderdil(this);
    }//GEN-LAST:event_btnOnderdilDeleteActionPerformed

    private void cmbOnderdilKatonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOnderdilKatonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbOnderdilKatonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOnderdilDelete;
    private javax.swing.JButton btnOnderdilReset;
    private javax.swing.JButton btnOnderdilSave;
    private javax.swing.JButton btnOnderdilUpdate;
    private javax.swing.JComboBox<String> cmbOnderdilKaton;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableOnderdil;
    private javax.swing.JTextField txtOnderdilHargaJual;
    private javax.swing.JTextField txtOnderdilId;
    private javax.swing.JTextField txtOnderdilIdKaton;
    private javax.swing.JTextField txtOnderdilIdRak;
    private javax.swing.JTextField txtOnderdilNamaOnderdil;
    private javax.swing.JTextField txtOnderdilSatuan;
    private javax.swing.JTextField txtOnderdilStok;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onChange(OnderdilModel model) {
        txtOnderdilId.setText(model.getIdOnderdil() + "");
        txtOnderdilIdKaton.setText(model.getIdKaton()+ "");
        txtOnderdilIdRak.setText(model.getIdRak()+ "");
        txtOnderdilNamaOnderdil.setText(model.getNamaOnderdil());
        txtOnderdilHargaJual.setText(model.getHargaJual()+"");
        txtOnderdilSatuan.setText(model.getSatuan());
        txtOnderdilStok.setText(model.getStok()+"");   
    }

    @Override
    public void onInsert(Onderdil onderdil) {
        tabelModel.add(onderdil);
    }

    @Override
    public void onDelete() {
        int index = tableOnderdil.getSelectedRow();
        tabelModel.remove(index);
    }

    @Override
    public void onUpdate(Onderdil onderdil) {
        int index = tableOnderdil.getSelectedRow();
        tabelModel.set(index, onderdil);
    }

    @Override
    public void valueChanged(ListSelectionEvent lse) {
        try {
            Onderdil model = tabelModel.get(tableOnderdil.getSelectedRow());
           txtOnderdilId.setText(model.getIdOnderdil() + "");
           txtOnderdilIdKaton.setText(model.getIdKaton()+ "");
           txtOnderdilIdRak.setText(model.getIdRak()+ "");
           txtOnderdilNamaOnderdil.setText(model.getNamaOnderdil());
           txtOnderdilHargaJual.setText(model.getHargaJual()+"");
           txtOnderdilSatuan.setText(model.getSatuan());
           txtOnderdilStok.setText(model.getStok()+"");  
        } catch (IndexOutOfBoundsException exception) {
            
        }
    }
    
    public void loadDatabase() throws SQLException, OnderdilException{
        OnderdilDao dao = SistemBengkelMotorDatabase.getOnderdilDao();
        tabelModel.setList(dao.selectAllOnderdil());
    }
}
