/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.timnas.sistembengkelmotor.view;

import edu.timnas.sistembengkelmotor.controller.RakController;
import edu.timnas.sistembengkelmotor.database.SistemBengkelMotorDatabase;
import edu.timnas.sistembengkelmotor.entity.Rak;
import edu.timnas.sistembengkelmotor.error.RakException;
import edu.timnas.sistembengkelmotor.event.RakListener;
import edu.timnas.sistembengkelmotor.model.RakModel;
import edu.timnas.sistembengkelmotor.model.TabelRakModel;
import edu.timnas.sistembengkelmotor.service.RakDao;
import java.sql.SQLException;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author teguhsis
 */
public class RakView extends javax.swing.JPanel implements RakListener, ListSelectionListener{

    private TabelRakModel tabelModel;
    private RakModel model;
    private RakController controller;
    
    public RakView() {
         tabelModel = new TabelRakModel();
        
        model = new RakModel();
        model.setListener(this);
        
        controller = new RakController();
        controller.setModel(model);
        
        initComponents();
        
        tableRak.getSelectionModel().addListSelectionListener(this);
        
        tableRak.setModel(tabelModel);
    }

    public JTable getTableRak() {
        return tableRak;
    }

    public JTextField getTxtRakId() {
        return txtRakId;
    }

    public JTextField getTxtRakLokasi() {
        return txtRakLokasi;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtRakLokasi = new javax.swing.JTextField();
        txtRakId = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableRak = new javax.swing.JTable();
        btnRakReset = new javax.swing.JButton();
        btnRakSave = new javax.swing.JButton();
        btnRakUpdate = new javax.swing.JButton();
        btnRakDelete = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel1.setText("Manajemen Lokasi Rak");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("ID Rak");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Lokasi");

        txtRakId.setEditable(false);

        tableRak.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableRak);

        btnRakReset.setText("RESET");
        btnRakReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRakResetActionPerformed(evt);
            }
        });

        btnRakSave.setText("SAVE");
        btnRakSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRakSaveActionPerformed(evt);
            }
        });

        btnRakUpdate.setText("UPDATE");
        btnRakUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRakUpdateActionPerformed(evt);
            }
        });

        btnRakDelete.setText("DELETE");
        btnRakDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRakDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRakId, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                            .addComponent(txtRakLokasi)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRakReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRakSave)
                        .addGap(18, 18, 18)
                        .addComponent(btnRakUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(btnRakDelete))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(145, 145, 145))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtRakId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRakLokasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRakReset)
                    .addComponent(btnRakSave)
                    .addComponent(btnRakUpdate)
                    .addComponent(btnRakDelete))
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRakResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRakResetActionPerformed
        // TODO add your handling code here:
         controller.resetRak(this);
    }//GEN-LAST:event_btnRakResetActionPerformed

    private void btnRakSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRakSaveActionPerformed
        // TODO add your handling code here:
        controller.insertRak(this);
    }//GEN-LAST:event_btnRakSaveActionPerformed

    private void btnRakUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRakUpdateActionPerformed
        // TODO add your handling code here:
         controller.updateRak(this);
    }//GEN-LAST:event_btnRakUpdateActionPerformed

    private void btnRakDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRakDeleteActionPerformed
        // TODO add your handling code here:
         controller.deleteRak(this);
    }//GEN-LAST:event_btnRakDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRakDelete;
    private javax.swing.JButton btnRakReset;
    private javax.swing.JButton btnRakSave;
    private javax.swing.JButton btnRakUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableRak;
    private javax.swing.JTextField txtRakId;
    private javax.swing.JTextField txtRakLokasi;
    // End of variables declaration//GEN-END:variables

     @Override
    public void onChange(RakModel model) {
        txtRakId.setText(model.getIdRak() + "");
        txtRakLokasi.setText(model.getLokasi());
    }

    @Override
    public void onInsert(Rak kasir) {
        tabelModel.add(kasir);
    }

    @Override
    public void onDelete() {
        int index = tableRak.getSelectedRow();
        tabelModel.remove(index);
    }

    @Override
    public void onUpdate(Rak kasir) {
        int index = tableRak.getSelectedRow();
        tabelModel.set(index, kasir);
    }

    @Override
    public void valueChanged(ListSelectionEvent e) {
        try {
            Rak model = tabelModel.get(tableRak.getSelectedRow());
            txtRakId.setText(model.getIdRak() + "");
            txtRakLokasi.setText(model.getLokasi());
        } catch (IndexOutOfBoundsException exception) {
            
        }
    }
    
    public void loadDatabase() throws SQLException, RakException{
        RakDao dao = SistemBengkelMotorDatabase.getRakDao();
        tabelModel.setList(dao.selectAllRak());
    }
}
